#服务信息
info:
    app:
        name: unit-demo
        description: 单元测试示例
        owner:
            - 杨磊
        emails:
            - yanglei@xingshulin.com
        env: ${SPRING_PROFILES_ACTIVE}
        build-number: ${BUILD_NUMBER}

#默认环境配置
server:
    port: 8010
logging:
    file: /logs/unit-demo/app.log
management:
    context-path: /manage
enhance:
    test:
        flag: true

spring:
    datasource:
        url: jdbc:mysql://192.168.64.66:33306/medchart_migrate?characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
        username: medchart_migrate
        password: medchart_migrate
        driver-class-name: com.mysql.jdbc.Driver
    test:
      database:

#dev环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: dev

#pub环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: qa
     #数据库
    datasource:
        url: jdbc:mysql://192.168.64.66:33306/medchart_migrate?characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
        username: medchart_migrate
        password: medchart_migrate
        driver-class-name: com.mysql.jdbc.Driver


#prod环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: prod
    datasource:
            url: jdbc:mysql://192.168.20.123:33306/medchart_migrate?characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
            username: medchartmigrate
            password: R7oQzU3wpT
            driver-class-name: com.mysql.jdbc.Driver